#!/usr/bin/python

import sys

def main():
  print "Hello there.  What is your name?"
  sys.stdout.flush()
  name = raw_input()
  print "Hello, {}".format(name)
  sys.stdout.flush()

if __name__ == "__main__":
  main()
